### ISSUE TITLE
【Web】セッションについて

### ISSUE THREAD

**Issue by Satish-Masa** [Satish-Masa/ec-study-backend#2]
セッションについて調べる

**Comment by Satish-Masa** [comment]
**セッション管理とは**
Httpプロトコルでは、クライアントからWebサーバーへのリクエストがあるたびに、クライアントとサーバー間でコネクションが成立し、リクエストに対するレスポンスがが行われ、コネクションが切断する。

セッション管理では、Cookieを利用するかhiddenフィールドを利用する。

IPA（https://www.ipa.go.jp/security/awareness/administrator/secure-web/chap6/6_session-1.html#:~:text=1)%20%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86%E3%81%A8%E3%81%AF,%E3%82%B3%E3%83%8D%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AF%E5%88%87%E6%96%AD%E3%81%95%E3%82%8C%E3%82%8B%E3%80%82&text=%E3%81%93%E3%81%AE%E4%BB%95%E7%B5%84%E3%81%BF%E3%82%92%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86%E3%81%A8%E5%91%BC%E3%82%93%E3%81%A7%E3%81%84%E3%82%8B%E3%80%82）

**Comment by Satish-Masa** [comment]
**HTTPプロトコルについて**
・World Wide Webの仕組み
WWWは、インターネット上の情報を様々な形式で参照することができるシステム

３つの要素から成り立っている。
1, 情報アクセス手段（URL: Uniform Resource Locator)
2, 情報表示フォーマット（HTML: HyperText Markup Language)
3, 情報通信プロトコル（HTTP: HyperText Transfer Protocol）

・HTTP通信について
クライアントからWebサーバーへWebブラウザが開始されてからの手順を以下に示す。
1, 80番ポートでTCPコネクションを確立させる
2, このポート上でHTTPコマンドに従ったデータのやり取りが行われる
3, データのやり取りが終わると接続を解除する
リクエストごとにコネクションを確立し、一回のデータ交換を終了するたびに接続を解除する。

**Comment by GuiltyMorishita** [comment]
https://www.amazon.co.jp/Web%E3%82%92%E6%94%AF%E3%81%88%E3%82%8B%E6%8A%80%E8%A1%93-HTTP%E3%80%81URI%E3%80%81HTML%E3%80%81%E3%81%9D%E3%81%97%E3%81%A6REST-WEB-PRESS-plus/dp/4774142042

**Comment by Satish-Masa** [comment]
紹介していただいた本を元に勉強中です。
しっかりと理解次第まとめようと思います。
